### ISSUE TITLE
Screenshots do not show all elements

### ISSUE THREAD

**Issue by dmorda** [stefanjudis/grunt-photobox#35]
Hi Stefan,

I love photobox and it works in 9 out of 10 cases for me. However, there are a few pages that may take a few milliseconds longer to load because they are doing javascript'ish things with photos such as using Foundation's Interchange. As a result, those photos are not displayed in the output files consistently.

Would there be a way to include a "delay" option that tells the task how long to wait for the page to load before taking the screenshot?

**Comment by stefanjudis** [comment]
Whooops - I kind of missed this one. Sorry for that. :(

Sure thing. 

Shouldn't also be a big deal.

The place to tackle might be:

https://github.com/stefanjudis/grunt-photobox/blob/master/tasks/lib/photoboxScript.js#L78

I'm not sure, when I'm available for that, but I'd gladly look over a PR. :)

**Comment by sbmadhav** [comment]
@dmorda , @stefanjudis : i hope pull request #44 closes out this issue.
