### ISSUE TITLE
Comparing 2 domains

### ISSUE THREAD

**Issue by dagomar** [stefanjudis/grunt-photobox#43]
So I am intrigued with this:

> If the localhost:8080 and 4waisenkinder.de are the same pages, we can easily now compare them by running: ['photobox:prod', 'photobox:dev'] as the images will have relative paths names.

However, there is no clarification to how I can actually use this. Where do I stick this?

**Comment by stefanjudis** [comment]
Hmm... Honestly it's been ages since i developed this... And i can't remember that s.th. like this is implemented at all. :(

**Comment by dagomar** [comment]
Alright! No worries, I'm still searching for the best way to do this. Would be a very good for tesing UI regressions.
